### ISSUE TITLE
Struct behaviour is incorrect

### ISSUE THREAD

**Issue by halostatue** [jrochkind/dig_rb#5]
As I was doing some debugging of my own version of `#dig` for an internal implementation in a gem, I discovered that my handling of `Struct` behaviour was incorrect—and yours is, too.

Surprisingly, the following works:

``` ruby
Q = Struct.new(:a, :b)
q = Q.new(1, 2)
q[:a] # => 1 # expected
q['a'] # => 1 # expected
q[1] # => 1 # surprising, but legal
q[3] # => IndexError: offset 3 too large for struct(size:2)
q.dig(1) # => 1 # surprising, but legal
q.dig(3) # => nil
```

So, `Struct` behaves like an `Object`, `Array`, and `Hash`. Your code forces keys to be Symbols, which is not correct per Ruby 2.3 behaviour.

**Comment by jrochkind** [comment]
Weird, I copied the logic directly from... some implementation, JRuby I think. And it passed all of the tests I could find in MRI at the latest ruby version at the time I wrote it. I wonder if they've changed the implementation in MRI, or if it just wasn't documented sufficiently. 

Are you interested in submitting a PR?

**Comment by jrochkind** [comment]
Or even some failing tests that show how it's supposed to work?

**Comment by jrochkind** [comment]
Ah, I understand the behavior you mean now. 

I could swear I copied the message langauge in `raise TypeError, "#{name} is not a symbol nor a string"` from _somewhere_, I wouldn't have come up with that myself. Weird, I wonder what happened. Thanks for the note though. PR certainly welcome if you feel so inclined. 

Aha, I copied it from OpenStruct -- OpenStruct does _not_ behave like a Struct in this case. How odd. 

```
irb(main):016:0> q = OpenStruct.new(:a => 1, :b => 2)
=> #<OpenStruct a=1, b=2>
irb(main):017:0> q.dig(1)
TypeError: 1 is not a symbol nor a string
```

**Comment by jrochkind** [comment]
I think I fixed it, the implementation is a bit messy. @halostatue , any comments before I release? a46d978

**Comment by halostatue** [comment]
That looks OK. My overall implementation is simpler, based on @Invoca’s implementation at [Invoca/ruby_dig](https://github.com/Invoca/ruby_dig). Before I release my code, I’ll probably be adding implementation guard clauses similar to what you have _in addition_ to the `RUBY_VERSION < '2.3'` check that I am currently doing.

``` ruby
if RUBY_VERSION < '2.3'
  class Cartage
    # An implementation of #dig for Ruby pre-2.3. Based originally on
    # {Invoca/ruby_dig}[https://github.com/Invoca/ruby_dig] with some
    # inspiration from {jrochkind/dig_rb}[https://github.com/jrochkind/dig_rb].
    module Dig #:nodoc:
      def dig(key, *rest)
        value = self[key]

        if value.nil? || rest.empty?
          value
        elsif value.respond_to?(:dig)
          value.dig(*rest)
        else
          fail TypeError, "#{value.class} does not have #dig method"
        end
      end
    end
  end

  #:stopdoc:
  class Array
    include Cartage::Dig
  end

  class Hash
    include Cartage::Dig
  end

  class Struct
    include Cartage::Dig

    # This override is necessary because <tt>Struct.new(:a).new(1)[0]</tt> is
    # *legal*. So we don't just care about NameError, but IndexError as well.
    def dig(name, *rest)
      super
    rescue IndexError, NameError
      nil
    end
  end

  class OpenStruct
    def dig(name, *rest)
      @table.dig(name.to_sym, *rest)
    rescue NoMethodError
      raise TypeError, "#{name} is not a symbol nor a string"
    end
  end
  #:startdoc:
end
```

**Comment by jrochkind** [comment]
Who knew so man of us were working on native ruby dig implementations, that's unfortunate. 

I have to admit I don't entirely understand your implementation, thanks for sharing, I'm going to try and figure it out. It is definitely simpler than mine. Maybe I'll try just copying yours entirely and demonstrating that it still passes all my tests.

**Comment by jrochkind** [comment]
@halostatue  note that `RUBY_VERSION < "2.3"` is not a totally reliable way to check version, eg    `'2.10' < '2.3'  # => true`

And your much simpler implementation does pass all the tests I've got. Maybe I'll just copy yours too if you don't mind?

**Comment by halostatue** [comment]
Not a problem.
